blank_issues_enabled: false
contact_links:
  - name: ✅ Connect US when your having questions.
    url: https://sophongo.github.io/sophdoc/
    about: If you have questions about product or need support building applicaion, please ask us