name: Size labeler

on:
- pull_request_target

jobs:
  size-labeler:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: "size/xs"
          xs_max_size: "9"
          s_label: "size/s"
          s_max_size: "29"
          m_label: "size/m"
          m_max_size: "99"
          l_label: "size/l"
          l_max_size: "499"
          xl_label: "size/xl"
          xl_max_size: "999"
          xll_label: "size/xll"
          xll_max_size: "1999"
          fail_if_xll: "false"
          message_if_xll: >
            This PR exceeds the recommended size of 2000 lines.
            Please make sure you are NOT addressing multiple issues with one PR.
            Note this PR might be rejected due to its size.
